os:
    - linux
    - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode10.1
env:
    - SWIFT_VERSION=swift-4.2
install:
    - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
script:
    - swift build
    - swift build -c release
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then swift test; fi
after_success:
    - eval "$(curl -sL https://codecov.io/bash)"
