os:
    - linux
    - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode11
env:
    - SWIFT_VERSION=swift-5.1
install:
    - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
script:
    - swift build -c release
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then swift test; fi
